### PR TITLE
update Requires.jl code to package extensions

### PR DESCRIPTION
**Pull request by ranocha**
Tests run fine locally on Julia v1.9.0-rc1

### CODE REVIEW

**Review by chriselrod — APPROVED** [review]
Thanks, didn't realize it was using ForwardDiff. 

Perhaps drop Requires.jl altogether, and load the file unconditionally on Julia 1.8 and older? You can still use the extension on 1.9.
This is what LoopVectorization.jl does, meaning the `@requires` will always trigger here:
https://github.com/JuliaSIMD/LoopVectorization.jl/blob/39ce8b9b46ee1eec6fae67bbbd6eddd3153ce084/src/LoopVectorization.jl#L263

**Comment by ranocha** [comment]
> Perhaps drop Requires.jl altogether, and load the file unconditionally on Julia 1.8 and older?

I'm not sure. I think the current approach is still fine since it does not load ForwardDiff.jl code when ForwardDiff.jl is not loaded. Thus, people not using ForwardDiff.jl will have increased latency.

**Comment by ranocha** [comment]
Sounds reasonable. Is [d5ac6bf](https://github.com/JuliaLinearAlgebra/Octavian.jl/pull/175/commits/d5ac6bf14862acdc54f2d6655f50f593f8eed4c6) what you had in mind?

**Comment by chriselrod** [comment]
> Sounds reasonable. Is [d5ac6bf](https://github.com/JuliaLinearAlgebra/Octavian.jl/pull/175/commits/d5ac6bf14862acdc54f2d6655f50f593f8eed4c6) what you had in mind?

Yes.

**Comment by chriselrod** [comment]
Mind replacing the `AbstractVecOrMat` with an `@eval` loop over `AbstractVector` and `AbstractMatrix`?

I know that is a bad thing to do.
The cost of adding methods is worse than O(N), so the marginal cost of extra methods increases.
This causes problems with packages adding methods to `LinearAlgebra.mul!` being extremely costly.

`_matmul!` at least should be cheap.

You're welcome to address this another way (e.g., address the `AbstractVector` `_matmul` specialization), but this seems fastest/easiest.

**Comment by ranocha** [comment]
Done in cb46881

**Comment by ranocha** [comment]
The multi-threaded Windows CI job ran out of memory
https://github.com/JuliaLinearAlgebra/Octavian.jl/actions/runs/4799970278/jobs/8540299392?pr=175#step:6:299

**Comment by chriselrod** [comment]
> The multi-threaded Windows CI job ran out of memory https://github.com/JuliaLinearAlgebra/Octavian.jl/actions/runs/4799970278/jobs/8540299392?pr=175#step:6:299

I restarted it.
Octavian's settings don't let me ignore test failures.

**Comment by ranocha** [comment]
Thanks!

**Comment by chriselrod** [comment]
Thanks for the PR!

**Pull request merged**
