### PR TITLE
An experiment to see if we can thread loop 3

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
I think something is not threadsafe inside loop 3. Is it `Aptr`? I.e. is `Aptr` the same across threads, and could that be the problem?

**Comment by DilumAluthge** [comment]
Does each thread inside loop 3 needs its own `Aptr`? Since each thread will be trying to copy into that location.

**Comment by chriselrod** [comment]
Oops, just saw this, yes, you're exactly right.

**Comment by chriselrod** [comment]
Every thread should make their own `Aptr` (which should be stack allocated, and hence free to do) and then pack it and use it for multiplication. So it shouldn't take any real management effort, unlike `Bptr`.

**Pull request closed without merging**
