### PR TITLE
[DO NOT MERGE] Run CI on Windows

### LINKED ISSUE #22: TODO: re-enable CI on Windows
The CI jobs on Windows are taking much longer than the Linux and macOS jobs. So I have disabled the Windows jobs for now.

Perhaps it's the specific CPUs that the Windows jobs are running on?

Maybe we could detect those CPUs, and run the tests with smaller matrices on those CPUs?

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@chriselrod Some of the Windows jobs run fast (e.g. 11 minutes), but other Windows jobs take a longer time (e.g. 56 minutes). Take a look at the CPUs for the fast Windows jobs versus the slow Windows jobs - anything stand out to you?

**Comment by chriselrod** [comment]
https://github.com/JuliaLinearAlgebra/Octavian.jl/pull/23/checks?check_run_id=1635842865
https://github.com/JuliaLinearAlgebra/Octavian.jl/pull/23/checks?check_run_id=1635842614
7 minutes vs 33 minutes, but the exact same CPU.

**Comment by DilumAluthge** [comment]
Could just be compile-time regressions in Julia 1.5 vs 1.7?

**Comment by DilumAluthge** [comment]
33 minutes isn't the worst thing in the world. It's the jobs that take 50 minutes (or longer) that I find annoying.

**Comment by chriselrod** [comment]
The fast one was Julia 1.7, so thankfully not a regression.

**Comment by chriselrod** [comment]
We should add types to the sizes here:
```julia
 (m, k, n) = (1, 2519, 2267)
  0.002439 seconds (2 allocations: 8.953 KiB)
 18.404083 seconds (19.98 M allocations: 784.395 MiB, 1.35% gc time)
 18.370855 seconds (19.98 M allocations: 769.841 MiB, 0.88% gc time)
 18.541612 seconds (19.97 M allocations: 769.730 MiB, 1.06% gc time)
```
For comparison:
```julia
(m, k, n) = (1, 2519, 2267)
  0.003294 seconds (2 allocations: 8.953 KiB)
  1.834332 seconds (1.90 M allocations: 101.713 MiB, 0.68% gc time)
  1.925558 seconds (1.90 M allocations: 101.713 MiB, 1.32% gc time)
  2.006441 seconds (1.90 M allocations: 101.713 MiB, 4.98% gc time)
```

But checkout those allocations when one or matrix is transposed!

**Pull request closed without merging**
