### PR TITLE
Separate the tests for coverage versus non-coverage

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
If this works well, we can reproduce this pattern in other repos where the test suite performance really slows down when code coverage is enabled.

**Comment by DilumAluthge** [comment]
Wow, look how fast!

**Comment by chriselrod** [comment]
Note that different matrix sizes hit different code paths.

**Comment by chriselrod** [comment]
Inside `matmul!` we have:
```julia
if M * K ≤ _Mc * _Kc && A isa DenseArray && C isa StridedArray && B isa StridedArray && #
        (stride(A,2) ≤ 72 || (iszero(stride(A,2) & (VectorizationBase.pick_vector_width(eltype(A))-1)) && iszero(reinterpret(Int,pointer(A)) & 63)))
    macrokernel!(C, A, B, _α, _β)
    return C
end
```
a check for whether we should just call `macrokernel!` directly.
And then similarly:
```julia
do_not_pack_B = (B isa DenseArray && (K * N ≤ _Kc * _Nc)) || N ≤ LoopVectorization.nᵣ
```
To check if we should skip packing B.
Because of the `DenseArray` checks, we'll still take both sides of each.

**Review by chriselrod — APPROVED** [review]

**Comment by DilumAluthge** [comment]
I wonder if this kind of pattern could be useful in other test suites (LoopVectorization.jl, VectorizationBase.jl, PaddedMatrices.jl, Gaius.jl, etc.).

Of course, it's only useful in cases where the test suite time greatly increases between coverage disabled and coverage enabled.

**Comment by chriselrod** [comment]
The beta != 0 code path actually isn't getting hit anymore.
It gets set to 1 for the second+ iteration of the `K` loop, but we could also just call `matmul!(C, A, B, true, true)`, for example.

**Comment by DilumAluthge** [comment]
> The beta != 0 code path actually isn't getting hit anymore.
> It gets set to 1 for the second+ iteration of the `K` loop, but we could also just call `matmul!(C, A, B, true, true)`, for example.

Yeah worst case we can just add unit tests to make up the coverage. I'll open a PR in a few minutes.

**Pull request merged**
