### PR TITLE
Fix type instability with static sized arrays

### PR DESCRIPTION
**Pull request by chriselrod**

### CODE REVIEW

**Review by DilumAluthge — CHANGES_REQUESTED** [review]
Can you bump the patch version number?

**Comment by chriselrod** [comment]
> Can you bump the patch version number?

Done.

**Review by DilumAluthge — APPROVED** [review]

**Comment by DilumAluthge** [comment]
If you click the "Enable auto-merge (squash)" button, then GitHub will automatically merge this PR after CI is green.

**Comment by chriselrod** [comment]
> If you click the "Enable auto-merge (squash)" button, then GitHub will automatically merge this PR after CI is green.

Cool, glad I don't have to check back in 3 hours after tests pass.

**Pull request merged**
