### PR TITLE
Bump VectorizationBase version

### PR DESCRIPTION
**Pull request by chriselrod**

### CODE REVIEW

**Comment by chriselrod** [comment]
Huh:
```julia
 (m, k, n) = (7, 8, 3103)
  0.000073 seconds (2 allocations: 84.953 KiB)
  0.016160 seconds (9.84 k allocations: 1.087 MiB)
  0.000062 seconds (2 allocations: 84.953 KiB)
  0.016199 seconds (9.84 k allocations: 1.079 MiB)
Matrix Multiply Float32: Test Failed at /Users/runner/work/Octavian.jl/Octavian.jl/test/matmul.jl:17
  Expression: #= /Users/runner/work/Octavian.jl/Octavian.jl/test/matmul.jl:17 =# @time(Octavian.matmul(A′, B′)) ≈ A′ * B′
   Evaluated: Float32[1.224844 1.9545381 … 1.9852811 1.408505; 0.98353696 2.1428268 … 1.6816484 2.0439897; … ; 1.2675793 1.754652 … 1.9716535 1.0884539; 1.449927 2.3375907 … 1.9986882 2.0846684] ≈ Float32[1.2161036 1.9420294 … 1.6376063 1.609231; 1.0730723 2.0454102 … 1.1516312 2.2028787; … ; 1.1950352 1.6860731 … 1.8151811 1.271324; 1.4606974 2.3462222 … 1.4238447 2.3655245]
Stacktrace:
 [1] macro expansion
   @ ~/work/Octavian.jl/Octavian.jl/test/matmul.jl:17 [inlined]
 [2] macro expansion
   @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.7/Test/src/Test.jl:1152 [inlined]
 [3] macro expansion
   @ ~/work/Octavian.jl/Octavian.jl/test/matmul.jl:2 [inlined]
 [4] top-level scope
   @ ./timing.jl:206
```

**Comment by DilumAluthge** [comment]
That's not good.

Also at least one of the jobs segfaulted.

**Comment by chriselrod** [comment]
Every failure was on old ivybridge macs.

**Comment by DilumAluthge** [comment]
No AVX2, right?

**Comment by chriselrod** [comment]
Yes, no AVX2, but these weren't integer tests, so it shouldn't have made a difference.
No FMA either, but that shouldn't cause a segfault.

Similar failures with Gaius:
https://github.com/MasonProtter/Gaius.jl/pull/66

**Comment by chriselrod** [comment]
https://github.com/MasonProtter/Gaius.jl/runs/1681476360?check_suite_focus=true
I just reran tests using 0.14.12, and the same CPU (Mac, ivybridge) passes.

So, this looks like a new regression with 0.15.

**Comment by DilumAluthge** [comment]
It sounds like Octavian and Gaius are doing their job! Catching regressions.

**Comment by chriselrod** [comment]
Okay, I'm fairly sure I've identified the problem, and where integers fit into the picture:

The segfault is in `unsafe_copyto_avx!`, where integers are used for the gathers/specifying pointer offsets.
Because the computer doesn't have `AVX2`, it only has 128-bit vectors for integer operations.
But it has 256-bit vectors of floating point numbers thanks to AVX.

Those 256 bit vectors fit 8 x `Float32`. To hold 8 integers in a 128 bit vector means it uses 8 x `Int16`.

The last test that passed involved 3 x 2519 matrix `A`. The first to fail involved 7 x 2519.
```julia
julia> typemax(Int16)
32767

julia> 3*2519*4 # length(A) * sizeof(eltype(A))
30228

julia> 7*2519*4 # length(A) * sizeof(eltype(A))
70532
```

The silly thing here is that gather instructions -- what those SIMD integers are being used for -- were also introduced in AVX2.

`Int32`s are really too small for most purposes, so I'll set `Int32` as the lower bound.

**Pull request merged**
